name: Deploy latest build to AWS
on:
  push:
    branches:
      - master

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - name: Executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            if pgrep node; then pkill node; fi
            cd ~/ng_cs_ft_v2
            git pull
            yarn build
            nohup serve -s build -l 9000 & > /dev/null
      
      - name: Disconnect tty
        if: success()
        run: exit 0
