name: Deploy latest build to AWS
on:
  push:
    branches:
      - master

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            killall node
            cd ~/ng_cs_ft_v2
            git pull
            yarn build
            nohup serve -s build -l 9000 &
            echo -ne '\n'
